name: Importar projeto do ZIP

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  importar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Descompactar projeto
        run: |
          unzip -o DynoMobile-beta3-corrigido.zip -d projeto
          cp -a projeto/. .
          rm -rf projeto
          rm DynoMobile-beta3-corrigido.zip

      
- name: Salvar arquivos no GitHub
  run: |
    rm -rf .github/workflows
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add -A
    git commit -m "Importar DynoMobile Beta 3 corrigido" || exit 0
    git push
